run: district_A district_B

district_A:
	./run_algo.py -s ES -d A
	./run_algo.py -s MS -d A
	./run_algo.py -s HS -d A

district_B:
	./run_algo.py -s ES -d B
	./run_algo.py -s MS -d B
	./run_algo.py -s HS -d B
